token: udy29x.ugyyk3tumg27atmr
podnet: 10.244.0.0/16

k3s_version: v1.17.3%2Bk3s1
extra_server_args: "--docker --no-deploy traefik --no-deploy servicelb --write-kubeconfig-mode 644"

flannel_version: "master"

username: ubuntu

dotfiles_repo: "https://malonso.me/bitbucket/scm/per/dotfiles.git"
dotfiles_repo_version: server
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "/home/{{ username }}/dotfiles"

dotfiles_home: "/home/{{ username }}"
dotfiles_files:
  - .zshrc
  - .tmux.conf
  - .vimrc
