#- hosts: all
#  roles:
#    - common
#      #    - k3s
##      
#- hosts: k3s
#  roles:
#    - k3s
##- hosts: master
##  roles:
##    - master
##
#- hosts: worker
#  roles:
#    - worker
#
- hosts: dotfiles
  roles:
    - dotfiles
#
#- hosts: nfs-ssd
#  roles:
#    - nfs-ssd
#
#- hosts: hdd
#  roles:
#    - hdd
#
- hosts: overclock
  roles:
    - overclock
