#- hosts: all
#  roles:
#    - common
#      #    - k3s
#      
#- hosts: master
#  roles:
#    - master
#
#- hosts: worker
#  roles:
#    - worker
#
#- hosts: dotfiles
#  roles:
#    - dotfiles
#
#- hosts: nfs-ssd
#  roles:
#    - nfs-ssd

- hosts: nfs-hdd
  roles:
    - nfs-hdd
