---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  register: hostname
  tags: hostname

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Enabling cgroup options at boot
  copy:
    src: nobtcmd.txt
    dest: /boot/firmware/nobtcmd.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: Set timezone to CET
  timezone:
    name: CET
  register: timezone

  #- name: Check custom fan config
  #  shell: cat /boot/firmware/usercfg.txt | grep -ozP "dtparam=poe_fan_temp0=75000,poe_fan_temp0_hyst=3000\ndtparam=poe_fan_temp1=77000,poe_fan_temp1_hyst=2000" 
  #  changed_when: false
  #  ignore_errors: true
  #  register: custom_fan_check
  #
  #- name: Change fan config
  #  blockinfile:
  #    path: /boot/firmware/usercfg.txt
  #    insertafter: EOF
  #    block: |
  #      dtparam=poe_fan_temp0=75000,poe_fan_temp0_hyst=3000
  #      dtparam=poe_fan_temp1=77000,poe_fan_temp1_hyst=2000
  #  when: custom_fan_check.stdout == ""
  #  register: custom_fan_config

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    upgrade: full

- name:  reboot the machine with all defaults
  reboot:
  when: timezone.changed or hostname.changed or cmdline.changed or custom_fan_config.changed
