---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  register: hostname
  tags: hostname

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: set timezone to CET
  timezone:
    name: CET
  register: timezone

- name: check custom fan config
  shell: cat /boot/firmware/usercfg.txt | grep -ozP "dtparam=poe_fan_temp0=75000,poe_fan_temp0_hyst=3000\ndtparam=poe_fan_temp1=77000,poe_fan_temp1_hyst=2000" 
  changed_when: false
  register: custom_fan_check

- name: change fan config
  blockinfile:
    path: /boot/firmware/usercfg.txt
    insertafter: EOF
    block: |
      dtparam=poe_fan_temp0=75000,poe_fan_temp0_hyst=3000
      dtparam=poe_fan_temp1=77000,poe_fan_temp1_hyst=2000
  when: custom_fan_check == ""

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    upgrade: full

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True
  when: timezone.changed or hostname.changed

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 15
    timeout: 120
  become: False
