---
- name: Install disk requirements
  apt:
    name: ['zfs-dkms','nfs-kernel-server','samba']
    state: latest

- name: Turn on NFS
  shell: zfs set sharenfs=on zfs

- name: Copy smb.conf
  template:
    src: smb.conf
    dest: /etc/samba/
    owner: root
    group: root
    mode: 0644

- name: Turn on Samba
  shell: zfs set sharesmb=on zfs
