---
- name: Install disk requirements
  apt:
    name: ['zfs-dkms','nfs-kernel-server','samba']
    state: latest

- name: Import ZFS pool
  shell: zpool import zfs -f

- name: Turn on NFS
  shell: zfs set sharenfs="rw,no_root_squash" zfs

- name: Copy smb.conf
  template:
    src: smb.conf
    dest: /etc/samba/
    owner: root
    group: root
    mode: 0644

- name: Turn on Samba
  shell: zfs set sharesmb=on zfs

- name: Reboot
  reboot:
